### ISSUE TITLE
Error: elementHandle.click: Element is not attached to the DOM

### ISSUE THREAD

**Issue by yogeshgadge** [bgotink/ngx-playwright#13]
Getting following error:-

```
    Error: elementHandle.click: Element is not attached to the DOM
    =========================== logs ===========================
    attempting click action
      waiting for element to be visible, enabled and stable
    ============================================================

        at /REDACTED/node_modules/@ngx-playwright/harness/element.js:230:14
        at PlaywrightElement.#perform (/REDACTED/node_modules/@ngx-playwright/harness/element.js:167:16)
        at SelectHarness.selectByText (/REDACTED/projects/app/e2e/harness/select.ts:48:9)
```

The way to reproduce is to use `MatSelectHarness` and do the following (in my case I am extending MatSelectHarness) which is going through the options and clicking on one of them.

```
    const options: MatOptionHarness[] = await this.getOptions(null, true);
    for (const opt of options) {
      const optText = await opt.getText();
      if (optText.trim() === text) {
        const h = await opt.host();
        //await h.focus();

        await opt.click(); /// <----  -- --  -- -- -- Throws above error
        break;
      }
    }
```

also I am using `respectShadowBoundaries`

```
createEnvironment(page).withOptions({ respectShadowBoundaries: true })
```

**Comment by yogeshgadge** [comment]
Not an issue.
It turned out that the opt.click() is occurring when the cdk select panel overlay was no longer open.
