### ISSUE TITLE
Automated installation

### ISSUE THREAD

**Issue by marcin-wosinek** [bgotink/ngx-playwright#6]
Hello,

I'm trying to use the package via automated installation `ng add @ngx-playwright/test`.

I tried with brand new ng-cli@14.0.6 generated app. The installation went smooth:

```
$ ng add @ngx-playwright/test
ℹ Using package manager: npm
✔ Found compatible package version: @ngx-playwright/test@0.2.6.
✔ Package information loaded.

The package @ngx-playwright/test@0.2.6 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
CREATE playwright/.gitignore (9 bytes)
CREATE playwright/playwright.config.js (515 bytes)
CREATE playwright/tsconfig.json (129 bytes)
CREATE playwright/screens/main-screen.js (236 bytes)
CREATE playwright/screens/screen.js (325 bytes)
CREATE playwright/specs/main-screen.e2e-spec.ts (306 bytes)
UPDATE angular.json (3280 bytes)
```

The attempt to run newly generated tests failed with:
```
$ ng e2e
✔ Browser application bundle generation complete.

Initial Chunk Files | Names         |  Raw Size
vendor.js           | vendor        |   1.52 MB |
polyfills.js        | polyfills     | 109.27 kB |
main.js             | main          |  47.98 kB |
runtime.js          | runtime       |   6.36 kB |
styles.css          | styles        | 736 bytes |

                    | Initial Total |   1.68 MB

Build at: 2022-07-14T10:38:30.041Z - Hash: bbfdf0fc087d50f7 - Time: 4613ms

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


✔ Compiled successfully.
/Users/marcinwosinek/workspace/e2e-playwright/playwright/playwright.config.js:1
import {join, dirname} from 'path';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Loader._requireOrImport (/Users/marcinwosinek/workspace/e2e-playwright/node_modules/@playwright/test/lib/loader.js:276:14)
    at Loader._requireOrImportDefaultObject (/Users/marcinwosinek/workspace/e2e-playwright/node_modules/@playwright/test/lib/loader.js:290:29)
    at Loader.loadConfigFile (/Users/marcinwosinek/workspace/e2e-playwright/node_modules/@playwright/test/lib/loader.js:79:31)
    at Runner.loadConfigFromResolvedFile (/Users/marcinwosinek/workspace/e2e-playwright/node_modules/@playwright/test/lib/runner.js:96:31)
    at runTests (/Users/marcinwosinek/workspace/e2e-playwright/node_modules/@playwright/test/lib/cli.js:153:40)
    at Ai.<anonymous> (/Users/marcinwosinek/workspace/e2e-playwright/node_modules/@playwright/test/lib/cli.js:70:7)
```

Adding `"type": "module"` to `package.json` resolves the issue, and with it in place the result is:
```
$ ng e2e
✔ Browser application bundle generation complete.

Initial Chunk Files | Names         |  Raw Size
vendor.js           | vendor        |   1.52 MB |
polyfills.js        | polyfills     | 109.27 kB |
main.js             | main          |  47.98 kB |
runtime.js          | runtime       |   6.36 kB |
styles.css          | styles        | 736 bytes |

                    | Initial Total |   1.68 MB

Build at: 2022-07-14T10:46:36.447Z - Hash: bbfdf0fc087d50f7 - Time: 2131ms

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


✔ Compiled successfully.

Running 0 test using 0 worker


=================
 no tests found.
=================
```

I think what is needed:
1. Some solutions for import types:
* adding `"type": "package"` change to the documentation, or
* adding it automatically as part of the installation, or
* using `require()` in tests instead of imports
2. A tweak to how the configuration finds tests. Simple switch from `js` to `ts` in `16   testMatch: '**/*.e2e-spec.ts',` was not enough

**Comment by bgotink** [comment]
Hmm, yup that's not good.
I've got a fix ready, but I first want to see if I can get this scenario running as part of the tests to ensure this won't break again.
